# Generated by Django 5.1.7 on 2025-04-28 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'İçerik Kategorisi',
                'verbose_name_plural': 'İçerik Kategorileri',
            },
        ),
        migrations.CreateModel(
            name='RecommendedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('short_description', models.TextField(verbose_name='Kısa Açıklama')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('image', models.ImageField(blank=True, null=True, upload_to='content_images/', verbose_name='Görsel')),
                ('related_element_name', models.CharField(blank=True, help_text='Ateş, Hava, Su veya Toprak değerlerinden birini girin', max_length=50, null=True, verbose_name='İlgili Mizaç Elementi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='profiles.contentcategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Önerilen İçerik',
                'verbose_name_plural': 'Önerilen İçerikler',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserContentInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.BooleanField(default=False, verbose_name='Görüntülendi mi?')),
                ('liked', models.BooleanField(default=False, verbose_name='Beğenildi mi?')),
                ('saved', models.BooleanField(default=False, verbose_name='Kaydedildi mi?')),
                ('viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Görüntülenme Tarihi')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interactions', to='profiles.recommendedcontent', verbose_name='İçerik')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_interactions', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı İçerik Etkileşimi',
                'verbose_name_plural': 'Kullanıcı İçerik Etkileşimleri',
                'unique_together': {('user', 'content')},
            },
        ),
    ]
