# Generated by Django 5.1.7 on 2025-04-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedcontent',
            name='related_element_name',
            field=models.CharField(choices=[('Ateş', 'Ateş'), ('Hava', 'Hava'), ('Su', 'Su'), ('Toprak', 'Toprak')], default='Ateş', help_text='Ateş, Hava, Su veya Toprak değerlerinden birini seçin', max_length=50, verbose_name='İlgili Mizaç Elementi'),
            preserve_default=False,
        ),
    ]
