# Generated by Django 5.1.6 on 2025-03-15 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing_algorithm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementtype',
            name='image',
        ),
    ]
