# Generated by Django 5.1.7 on 2025-03-16 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_algorithm', '0002_remove_elementtype_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementtype',
            name='recommendations',
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Önerilerin sıralaması için kullanılabilir.')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='testing_algorithm.elementtype')),
            ],
        ),
    ]
