# Generated by Django 5.1.7 on 2025-03-16 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_algorithm', '0003_remove_elementtype_recommendations_recommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing_algorithm.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing_algorithm.question')),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='testing_algorithm.testresult')),
            ],
            options={
                'unique_together': {('test_result', 'question')},
            },
        ),
    ]
