# Generated by Django 5.1.7 on 2025-03-17 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_algorithm', '0004_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResultDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('element_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing_algorithm.elementtype')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing_algorithm.question')),
                ('selected_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing_algorithm.choice')),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='testing_algorithm.testresult')),
            ],
            options={
                'verbose_name': 'Test Sonuç Detayı',
                'verbose_name_plural': 'Test Sonuç Detayları',
            },
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
