# Generated by Django 5.1.7 on 2025-03-22 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing_algorithm', '0005_testresultdetail_delete_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
