# Generated by Django 5.1.7 on 2025-04-21 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_algorithm', '0006_delete_recommendation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testresult',
            old_name='air_score',
            new_name='moist_score',
        ),
        migrations.RenameField(
            model_name='testresult',
            old_name='earth_score',
            new_name='warm_score',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='element_type',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='fire_score',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='water_score',
        ),
        migrations.RemoveField(
            model_name='testresultdetail',
            name='element_type',
        ),
        migrations.AddField(
            model_name='elementtype',
            name='is_moist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='elementtype',
            name='is_warm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('WARM', 'Sıcak/Soğuk Sorusu'), ('MOIST', 'Nemli/Kuru Sorusu')], default='WARM', max_length=5),
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Önerilerin sıralaması için kullanılabilir.')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='testing_algorithm.elementtype')),
            ],
        ),
    ]
