# Generated by Django 5.1.7 on 2025-04-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_algorithm', '0007_rename_air_score_testresult_moist_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('WARM', 'Sıcak/Soğuk Sorusu'), ('WARM_MOIST', 'Sıcak Mizaçlar için Nemli/Kuru Sorusu'), ('COLD_MOIST', 'Soğuk Mizaçlar için Nemli/Kuru Sorusu')], default='WARM', max_length=10),
        ),
    ]
