# Generated by Django 5.1.7 on 2025-04-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_algorithm', '0008_alter_question_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='score',
        ),
        migrations.AddField(
            model_name='choice',
            name='cold_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='dry_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='moist_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='warm_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='raw_cold_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='raw_dry_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='raw_moist_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='raw_warm_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresultdetail',
            name='cold_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresultdetail',
            name='dry_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresultdetail',
            name='moist_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresultdetail',
            name='warm_score',
            field=models.IntegerField(default=0),
        ),
    ]
